
<script type="text/javascript">

checked=false;
function chkAll () {
	var arr = new Array();
	if (checked == false)
	  {
	   checked = true
	  }
	else
	  {
	  checked = false
	  }
	arr = document.getElementsByTagName('input');
	if (arr.length>1)
	{	
		for (var i =0; i < arr.length; i++) 
		{
			if(arr[i].type == 'checkbox') arr.item(i).checked=  checked;
		}
	}
	else
	{
		alert('هیچ مطلبی لیست نشده است!');
	}
}
//-------------------------
function doAct(formAction)
{
	var arr = new Array();
	var j=0;
	arr = document.getElementsByTagName('input');
	for (var i =0; i < arr.length; i++) 
	{
		if((arr[i].type == 'checkbox')&(arr.item(i).checked==true))
			 j++;
	}
	if (j==0)
	{
		alert('هیچ کاربری انتخاب نشده است');
	}
	else
	{
		document.forms[0].action	= formAction;
		document.forms[0].submit();
	}
}
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<div class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

<div style="margin:0 auto;" >
<!--<div class="ui-corner-all ui-widget-header"><h1><?php echo $this->escape($this->title);?></h1></div>-->
  	<?php 
		if ( !empty($this->msg))
		{
			if(is_array($this->msg[0])) $this->msg = $this->msg[0];
			//echo '<div class="ui-state-error ui-corner-all"	>';
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		 	//echo'</div>';
		}
	?>
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
<style>
.d1{width:5%;}.d2{width:3%;}.d3{width:25%;}.d4{width:20%;}.d5{width:15%;}.d6{width:5%;}.d7{width:13%;}.d8{width:10%;}.d9{width:7%;}
</style>
		<form name="frm0" action="" method="post" style="margin-top:3px;">
		  <table border="1" cellspacing="0"  class="showborder ui-widget" style="table-layout:fixed;">
			<tr  class="ui-widget-header">
			  <th class="d1">ردیف</th>
			  <th class="d2"><input type="checkbox" name="tgl" id="tgl" onclick="chkAll();"/></th>	  
			  <th class="d3">نام واقعی</th>
			  <th class="d4">نام کاربری</th>	  
			  <th class="d5">تاریخ عضویت</th>	  
			  <th class="d6">وضعیت</th>
			  <th class="d7">عمل</th>	  
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr class="ui-widget-content" title="">
				<td class="d1"><?php echo $j+$this->start;			?></td>	
				<td class="d2">
					<center><input value="<?php echo $i['id']; ?>" name="chk[]" type="checkbox" /></center>
				</td>	
		
				<td class="d3">	
				<div class="lnk" style="width:230px; overflow:hidden;padding:3px;">
					<a  href="/usermanager/frmregister/index/id/<?php echo $i['id'].$this->env;?>" title=""> 
						<?php echo $i['first_name'].' '.$i['last_name']?>											
					</a>
				</div>
				</td>
				<td class="d4"><div style="width:170px; overflow:hidden;"><?php echo $i['username'] ?></div></td>
				<td class="d5"><?php echo ger_to_fa($i['crt_date'])	?></td>	  
				<td class="d6">
					<?php if($i['is_active']=='1')
							{
								echo "<a href='/usermanager/doact/deactivate/id/".$i['id']."/st/".$this->start . $this->env."'><center><img src='/img/publish_g.png'></center></a>";
							}
							else
							{
								echo "<a href='/usermanager/doact/activate/id/".$i['id']."/st/".$this->start . $this->env."'><center><img src='/img/publish_x.png'></center></a>";
							}
					?>
				</td>	    
				<td class="d7">
					<a href="/usermanager/frmregister/index/id/<?php echo $i['id'].$this->env;?>">ویرایش</a>&nbsp;|&nbsp;
					<a href="/usermanager/doact/delconfirm/id/<?php echo $i['id'].$this->env;?>">حذف</a>
				</td>	    
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="javascript:doAct('/usermanager/doact/delconfirm<?php echo $this->env;?>');" >حذف</a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="javascript:doAct('/usermanager/doact/deactivateconfirm<?php echo $this->env;?>');" >غیرفعال سازی</a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="javascript:doAct('/usermanager/doact/activateconfirm<?php echo $this->env;?>');" >فعال سازی</a>
</span>
<br />
<br />
		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,$this->BaseUrl(),$this->env);?>
		</div>

		</form>
<?php
	}
	else
	{
		echo '<h1>هیچ مطلبی یافت نشد!</h1>';
		echo paging($this->count,$this->start,$this->limit,$this->BaseUrl(),$this->env);
		
	}
?>
</div>
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
<?php 
function paging	($count,$start,$limit,$BaseUrl,$env)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center" '
							.  ' style="text-align:right" width="100%"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/rtcmanager/frmlistcnt/index/st/".$back. $env ."' class='btn ui-state-default ui-corner-all'><font  size='2'>صفحه قبل</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/rtcmanager/frmlistcnt/index/st/".$i. $env ."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/rtcmanager/frmlistcnt/index/st/".$this1. $env ."' class='btn ui-state-default ui-corner-all'><font  size='2'>صفحه بعد</font></a>";
					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
//-------------
function ger_to_fa($date)
{
	if ($date=='')
	{
		return	 NULL;
	}
	else 
	{
		$arr	= explode(' ',$date)	;
		$d		= explode('-',$arr[0])	;
		$pdate	= new Rasta_Pdate;
		$arr[0] = implode('-',$pdate->gregorian_to_persian($d[0],$d[1],$d[2]));
		return  implode(' ',$arr);
	}	
}
//---------------
?>