<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  .click(function(){ $('#facebox #confirm').attr('href', '/comment/manager/del/id/'+$(this).attr('val')); })
    })
</script>
<style>
h2,h3,h4{ margin:0px;padding:0px;}

.d1{width:3%;}.d2{width:20%;}.d3{width:15%;}.d4{width:23%;} .d5{width:23%;}.d6{width:6%;}.d7{width:10%;}
td.dtext{ border-bottom-color:#FF0000; text-align:justify;padding:10px;}

</style>

<?php 
if (!empty($this->errormsg))
{

echo '<blockquote style="color:#CC3300;line-height:1.5;direction:'.$this->translate->_('dir').';">';
foreach ($this->errormsg as $errormsg)
{
	   echo  "<h4>".$errormsg."</h4>";
}
echo'</blockquote>';
}


?>

<div class="art-article" style="float:none;margin:0 auto;" > 
	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h3 class="art-postheader" style="direction:<?php echo $this->translate->_('dir'); ?>;text-align:center;">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h3>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<div id="contentinfos" style="direction:<?php echo $this->translate->_('dir');?>;text-align:justify;font-family:tahoma;font-size:12px;">
<?php echo $this->translate->_('n');?>:&nbsp;<?php echo $this->ContentInfos['title'];?><br /><br />
<?php echo $this->translate->_('o');?>:&nbsp;<?php $commSetting = array('', $this->translate->_('q'), $this->translate->_('r')); echo $commSetting[$this->ContentInfos['setting'][3]]?><br /><br />
<?php echo $this->translate->_('p');?>:&nbsp;<?php echo $this->count;?><br /><br />
</div>
<?php if(is_array($this->list))
{ ?>
	  <table border="1" cellspacing="0"  class="showborder ui-widget" style="table-layout:fixed;width:100%;">
		<tr>
		  <th class="d1" ><?php echo $this->translate->_('f');?></th>  
		  <th class="d2" ><?php echo $this->translate->_('d');?></th>
		  <th class="d3" ><?php echo $this->translate->_('g');?></th>	  
		  <th class="d4" ><?php echo $this->translate->_('c');?></th>	  
		  <th class="d5" ><?php echo $this->translate->_('h');?></th>	  
		  <th class="d6" ><?php echo $this->translate->_('j');?></th>	  
		  <th class="d7" ><?php echo $this->translate->_('i');?></th>	  
		</tr>
	<?php $i=1; foreach($this->list as $comment){ ?>
		<tr>
			<td class="d1" ><?php echo $i+$this->start; ?></td>		
			<td class="d2" ><?php echo $comment['name']; ?></td>
			<td class="d3" ><?php echo ger_to_fa($comment['time']); ?></td>
			<td class="d4" >
		<?php if(!empty($comment['site'])): ?>
			<a href="http://<?php echo $comment['site']; ?>" title="<?php echo $comment['site']; ?>"><?php echo $comment['site']; ?><!--<?php echo $this->translate->_('c');?>--></a>
		<?php endif; ?>
			</td>
			<td class="d5" ><?php echo $comment['email']; ?></td>
			<td class="d6" >
				<?php $status_lable	= array('', array($this->translate->_('m'), 'publish_x.png', '2'),
												array($this->translate->_('l'), 'publish_g.png', '1')
											);
				 ?>
					<a href="/comment/manager/status/id/<?php echo $comment['id'].':'.$status_lable[ $comment['status'] ][2].$this->newUriParams;?>">
					<img src="/img/<?php echo $status_lable[ $comment['status'] ][1]; ?>" title="<?php echo $status_lable[ $comment['status'] ][0]?>"></a>
			</td>
			<td class="d7" >
					<center>
					<a href="#">
					<img src="/img/edit.png" title="<?php echo $this->translate->_('c');?>"></a>|
					<a href="#dlg_comment" rel="facebox"  val="<?php echo $comment['id'].$this->newUriParams;?>">
					<img src="/img/delete.png" title="<?php echo $this->translate->_('c');?>"></a>
					</center>
			</td>
		</tr>
		<tr>
			<td colspan="7" class="dtext"><?php echo $comment['text']; ?></td>
		</tr>
	
		<?php $i++;} ?>
	  </table>
		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,'/comment/manager/index', $this->translate, $this->newUriParams);?>
		</div>
<?php 	
}
else
{
?>
	<?php echo $this->translate->_('e'); ?>
<?php 
}
 ?>
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>





</div>
<div id="dlg_comment" style="display:none;">
<?php echo $this->translate->_('s');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" ><?php echo $this->translate->_('t');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$('#facebox a.close').click();" ><?php echo $this->translate->_('u');?></a>
</span>
<br />
<br />
</div>
<?php
function ger_to_fa($date)
{
	if ($date=='')
	{
		return	 NULL;
	}
	else 
	{
		$arr	= explode(' ',$date)	;
		$d		= explode('-',$arr[0])	;
		$pdate	= new Rasta_Pdate;
		$arr[0] = implode('-',$pdate->gregorian_to_persian($d[0],$d[1],$d[2]));
		return  implode(' ',$arr);
	}	
}

function paging	($count,$start,$limit,$BaseUrl, $translate, $newUriParams)
{
	$newUriParams	= preg_replace('/\/st\/\d+/', '', $newUriParams);
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$back . $newUriParams ."' class='btn ui-state-default ui-corner-all'><font  size='2'>" 
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/st/".$i. $newUriParams ."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$this1. $newUriParams ."' class='btn ui-state-default ui-corner-all'><font  size='2'>"										
								.  $translate->_('next page')."</font></a>"; 

					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}


?>
