<script type="text/javascript">
$(document).ready(function(){
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
		return false;
	})
})
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.td_title{width:135px;}.td_box{width:420px;}.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="<?php echo $this->form_action;?>" method="post">
	<table style="width: 840px; margin: 0pt auto; text-align: right; direction:<?php echo $this->translate->_('dir');?>;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('title');?></label></td>
				<td class="td_box">
<?php
$tstat	= (WBSiD==='1' or $this->data['ct_wbs']==WBSiD or !is_numeric($this->data['cid']))?'':'readonly="true"';
?>

					<input type="text" class="inputBox" size="35" maxlength="100" name="title" <?php echo $tstat; ?> value="<?php echo $this->data['title']; ?>">
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('k'); ?></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="10" name="singpage" value="<?php echo $this->data['singpage']; ?>" >
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('status'); ?></label></td>
				<td class="td_box">
					<input type="radio" name="status" value="1" <?php echo (($this->data['status']==1)?'checked="checked"':''); ?> />
						<?php echo $this->translate->_('active'); ?>&nbsp;&nbsp;&nbsp;&nbsp;
					<input type="radio" name="status" value="0" <?php echo (($this->data['status']==1)?'':'checked="checked"'); ?> />
						<?php echo $this->translate->_('inactive'); ?>
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('h');?></label></td>
				<td id="userGroups" class="td_box">
				<style>#userGroups div{<?php echo $this->translate->_('stylea'); ?>}</style>
				<?php
					$currentGroups	= array();
					if(!empty($this->data['user_group'])) $currentGroups	= array_filter(explode('/', $this->data['user_group']));
					if(is_array($this->wbsUserGroups))
						foreach($this->wbsUserGroups as $value)
						{
							$checkedState = '';
							if( in_array($value['id'],$currentGroups) ) $checkedState = 'checked="checked"';
							echo '<div><input type="checkbox" name="ugroup[]" value="'.$value['id'].'" '.$checkedState.' /><label>&nbsp;'.$value['title'].'</label></div>'; 
						}
				?>
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('i');?></label></td>
				<td id="userGroups" class="td_box">
				<?php
					$currentGroups	= array();
					if($this->data['c_usrgs']=='/0/')		$currentGroups[]= 0;
					elseif(!empty($this->data['c_usrgs']))	$currentGroups	= array_filter(explode('/', $this->data['c_usrgs']));
					$this->wbsUserGroups[]	= array('id'=>0, 'title'=>$this->translate->_('m'));
					foreach($this->wbsUserGroups as $value)
					{
						$checkedState = '';
						if( in_array($value['id'],$currentGroups) ) $checkedState = 'checked="checked"';
						echo '<div><input type="checkbox" name="cusrgs[]" value="'.$value['id'].'" '.$checkedState.' /><label>&nbsp;'.$value['title'].'</label></div>'; 
					}
				?>
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('j');?></label></td>
				<td id="userGroups" class="td_box">
				<?php
					$current	= array();
					if($this->data['c_scens']=='/0/')		$current[]	= 0;
					elseif(!empty($this->data['c_scens']))	$current	= array_filter(explode('/', $this->data['c_scens']));
					$this->wbstaxoterms[]	= array('id'=>0, 'title'=>$this->translate->_('m'));
					foreach($this->wbstaxoterms as $value)
					{
						$checkedState = '';
						if( in_array($value['id'],$current) ) $checkedState = 'checked="checked"';
						echo '<div><input type="checkbox" name="cscens[]" value="'.$value['id'].'" '.$checkedState.' /><label>&nbsp;'.$value['title'].'</label></div>'; 
					}
				?>
				</td>
			</tr>
<?php
if(WBSiD==='1' or $this->data['ct_wbs']==WBSiD or !is_numeric($this->data['cid'])){
?>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('language'); ?></label></td>
				<td class="td_box">
					<select name="lang">
						<?php if(is_array($this->wbsLangs)){ foreach($this->wbsLangs as $langs){ ?>
						<option value="<?php echo $langs['la_code']; ?>" <?php echo (($langs['la_code']==$this->data['lang'])?'selected="selected"':''); ?> >
						<?php echo $langs['la_title']; ?></option>
						<?php }} ?>
					</select>
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('l'); ?></label></td>
				<td class="td_box">
					<textarea name="editor" rows="20" cols="75" dir="ltr"><?php echo $this->escape( stripslashes($this->data['editor']) ); ?></textarea>
				</td>
			</tr>

<?php
}
?>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['cid']; ?>" name="cid" />
	</form>
			

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#"><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/rtcmanager/rtctype/frmlist#fragment-3" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
