<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
h2,h3,h4{ margin:0px;padding:0px;}
</style>

<?php 
if (!empty($this->errormsg))
{

echo '<blockquote style="color:#CC3300;line-height:1.5;direction:'.$this->translate->_('dir').';">';
foreach ($this->errormsg as $errormsg)
{
	   echo  "<h4>".$errormsg."</h4>";
}
echo'</blockquote>';
}


?>

<div class="art-article" style="width:500px;float:none;margin:0 auto;" > 
	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h3 class="art-postheader" style="direction:<?php echo $this->translate->_('dir'); ?>;text-align:center;">
							<span class="art-postheader"><?php echo $this->contentTitle; ?></span>
						</h3>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php if(is_array($this->list))
{ ?>
	<?php foreach($this->list as $comment){ ?>
	<div style="width:90%;border:1px solid #608DA9;margin:5px auto;direction:<?php echo $this->translate->_('dir'); ?>;font-family:tahoma;font-size:12px;">
		<div style="width:100%;height:25px;background-color:#b9d0dc;">
			<div style="width:49%;float:right;">
	<?php echo $this->translate->_('d').':&nbsp;&nbsp;'.$comment['name']; ?>
			</div>
			<div style="width:49%;float:left;text-align:left;padding-left:5px;">
	<?php echo ger_to_fa($comment['time']); ?>
			</div>
		</div>
		<div style="width:99%;height:auto;border-bottom:1px solid #608DA9;padding:10px 0.5%;">
	<?php echo $comment['text']; ?>
		</div>
		<div style="width:100%;height:25px;">
	<?php if(!empty($comment['site'])){ ?>
	<span style="font-size:12px;">
		<a href="http://<?php echo $comment['site']; ?>" style="float:left;text-decoration:none; margin-left:5px;"><?php echo $this->translate->_('c'); ?></a>
	</span>
	<?php } ?>
		</div>
	
	</div>
	
<?php 	} ?>
		<div id="pagingcontainer">
		<style>
		#pagingcontainer table { float: none; margin: 0 auto;} #pagingcontainer td {  border:none;}
		</style>
					<?php paging($this->count,$this->start,$this->limit,'/comment/index/index', $this->translate, $this->newUriParams);?>
		</div>
<?php

}
else
{
	echo $this->nolistmsg;
}
 ?>
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>
	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h4 class="art-postheader" style="direction:<?php echo $this->translate->_('dir'); ?>;text-align:center;">
							<span class="art-postheader"><?php echo $this->translate->_('b'); ?></span>
						</h4>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php echo $this->render('form.phtml') ?>
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>





</div>
<script>
//alert(document.cookie);
</script>
<?php
function ger_to_fa($date)
{
	if ($date=='')
	{
		return	 NULL;
	}
	else 
	{
		$arr	= explode(' ',$date)	;
		$d		= explode('-',$arr[0])	;
		$pdate	= new Rasta_Pdate;
		$arr[0] = implode('-',$pdate->gregorian_to_persian($d[0],$d[1],$d[2]));
		return  implode(' ',$arr);
	}	
}
function paging	($count,$start,$limit,$BaseUrl, $translate, $newUriParams)
{
	$newUriParams	= preg_replace('/\/st\/\d+/', '', $newUriParams);
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center" dir="'.$translate->_('dir').'"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$back . $newUriParams ."' class='btn ui-state-default ui-corner-all'><font  size='2'>" 
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/st/".$i. $newUriParams ."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$this1. $newUriParams ."' class='btn ui-state-default ui-corner-all'><font  size='2'>"										
								.  $translate->_('next page')."</font></a>"; 

					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
?>
