<?php

?>

<script type="text/javascript">
$(document).ready(function(){
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
		return false;
	})
})
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.td_title{width:135px;}.td_box{width:420px;}.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="<?php echo $this->form_action;?>" method="post">
	<table style="width: 840px; margin: 0pt auto; text-align: right; direction:<?php echo $this->translate->_('dir');?>;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('title');?> *</label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="title" value="<?php echo $this->data['title']; ?>">
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('y');?></label></td>
				<td class="td_box">
					<select class="inputBox" name="lang" style="width:150px;">
						<option value="fa"><?php echo $this->translate->_('w');?></option>
					</select>
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('x');?></label></td>
				<td class="td_box">
				<?php $scdata	= ($this->data['scdata']=='on')?'checked="checked"':''; ?>
					<input type="checkbox" class="inputBox" name="scdata" <?php echo $scdata;?>>&nbsp;<?php echo $this->translate->_('v');?>&nbsp;&nbsp;&nbsp;&nbsp;
				<?php $ugdata	= ($this->data['ugdata']=='on')?'checked="checked"':''; ?>
					<input type="checkbox" class="inputBox" name="ugdata" <?php echo $ugdata;?>>&nbsp;<?php echo $this->translate->_('u');?>
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('s');?> *</label></td>
				<td class="td_box">
					<textarea cols="75" rows="10" dir="ltr" name="script"><?php echo htmlspecialchars($this->data['script']); ?></textarea>
				</td> 
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('r');?> *</label></td>
				<td class="td_box">
					<textarea cols="75" rows="10" dir="ltr" name="listskin"><?php echo htmlspecialchars($this->data['listskin']); ?></textarea>
				</td> 
			</tr>

		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['gid']; ?>" name="gid" />
	</form>
			

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#"><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/gadget/admin/frmlist#fragment-3" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
