<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
.d1{width:10%;}.d2{width:44%;}.d3{width:44%;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg){echo  "<h4>".$msg."</h4>";}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder" style="width:600px;margin:0 auto;">
			<tr>
			  <th class="d1"><?php echo $this->translate->_('c');?></th>  
			  <th class="d2"><?php echo $this->translate->_('title');?></th>
			  <th class="d3"><?php echo $this->translate->_('g');?></th>	    
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr>
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" ><a href="/gad/<?php echo $i['id'];?>" ><?php echo $i['title'];?></a></td>
				<td class="d3" >
					<a href="/gadget/admin/frmconfig/id/<?php echo $i['id'];?>#fragment-3"><?php echo $this->translate->_('z');?></a>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,$this->BaseUrl(), $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('ah');
	}
?>

<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/gadget/admin/publicgadlist/st/".$back ."' class='btn'><font  size='2'>"
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/gadget/admin/publicgadlist/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/gadget/admin/publicgadlist/st/".$this1."' class='btn'><font  size='2'>"
								.  $translate->_('next page')."</font></a>";
					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}

?>