<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  .click(function(){ $('#facebox #confirm').attr('href', '/dashboard/page/del/id/'+$(this).attr('val')); })
    })
</script>

<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;/*width:650px;border:1px solid;*/height:auto;}
.d1{width:5%;}.d2{width:30%;}.d3{width:22%;}.d4{width:18%;}.d4{width:15%;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title_site); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder ui-widget" style="table-layout:fixed;width:80%;margin:0 auto;">
			<tr  class="ui-widget-header">
			  <th class="d1" ><?php echo $this->translate->_('b');?></th>  
			  <th class="d2" ><?php echo $this->translate->_('c');?></th>
			  <th class="d3" ><?php echo $this->translate->_('d');?></th>	  
			  <th class="d4" ><?php echo $this->translate->_('e');?></th>	  
			  <th class="d5" ><?php echo $this->translate->_('f');?></th>	  
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr class="ui-widget-content" title="<?php echo $i['description'] ?>">
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" ><a title="<?php echo $this->translate->_('g');?>" target="_blank" href="/admin/<?php echo 'page/'.$i['local_id'];?>" ><?php echo $i['wb_page_title'];?></a></td>
				<td class="d3" dir="ltr" ><a title="<?php echo $this->translate->_('h');?>" target="_blank" href="/<?php echo 'page/'.$i['local_id'];?>"><?php echo '/page/'.$i['local_id'];?></a></td>
				<td class="d4" ><?php if ($i['page_state']==0){echo $this->translate->_('i');}else if ($i['page_state']==1){echo $this->translate->_('j');}else if($i['page_state']==2){echo $this->translate->_('k');}?></td>
				<td class="d5" >
					<a href="/dashboard/page/frmedit/id/<?php echo $i['local_id'];?>#fragment-2"><?php echo $this->translate->_('l');?></a>&nbsp;|&nbsp;
					<a href="#dlg_pages" class="sel_page" val="<?php echo $i['local_id'];?>" name="<?php echo $i['wb_page_title'];?>" rel="facebox"><?php echo $this->translate->_('o');?></a>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>


		<div id="pagingcontainer">
			<?php paging($this->count,$this->start,$this->limit,$this->BaseUrl(), $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('p');
		//echo paging($this->count,$this->start,$this->limit,$this->BaseUrl(),$this->env);
		
	}
?>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/dashboard" ><?php echo $this->translate->_('q');?></a>
</span>
<br />
<br />

                                                  
                                                <!-- /article-content -->
                                            </div>
                                            <div class="cleared"></div>
                            </div>
                            
                            		<div class="cleared"></div>
                                </div>
                            </div>
</div>

<div id="dlg_pages" style="display:none;">
<?php echo $this->translate->_('s');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" ><?php echo $this->translate->_('m');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$('#facebox a.close').click();" ><?php echo $this->translate->_('n');?></a>
</span>
<br />
<br />
</div>


<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/dashboard/page/frmlist/st/".$back."' class='btn ui-state-default ui-corner-all'><font  size='2'>"
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/dashboard/page/frmlist/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/dashboard/page/frmlist/st/".$this1."' class='btn ui-state-default ui-corner-all'><font  size='2'>"
								.  $translate->_('next page')."</font></a>";
					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
//---------------
?>