<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
#directorylist{text-align:right;margin:15px 30px;}
#directorylist ul{margin-right:20px;margin-top:10px;}
#directorylist li{font-family:tahoma;font-size:13px;line-height:1.5;}
</style>

<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->translate->_('a');?></span>
						</h2>
					</div>
					<div class="art-postcontent">

<ol id="directorylist">

	<li><a href="/help/directory/parti/season/login#fragment-6">ورود به بخش مدیریت سایت</a></li>
	<li><a href="/help/directory/parti/season/dashboard-intro#fragment-6">آشنایی با محیط داشبورد</a></li>
	<li><a href="/help/directory/parti/season/pageadmin-intro#fragment-6">آشنایی با محیط مدیریت صفحات</a></li>
	<li>مدیریت سایت
		<ul>
			<li><a href="/help/directory/parti/season/sitesetting#fragment-6">تنظیمات سایت</a></li>
			<li>مدیریت صفحات
				<ul>
					<li></li>
				</ul>
			</li>
			<li>مدیریت فایل‌ها
				<ul>
					<li></li>
				</ul>
			</li>
			<li>مشاهده سایت</li>
			<li>قاصدک
				<ul>
					<li>لیست قاصدک‌ها</li>
					<li>ایجاد قاصدک جدید</li>
					<li>ویرایش قاصدک</li>
					<li>حذف قاصدک</li>
				</ul>
			</li>
			<li>داشبورد اختصاصی
				<ul>
					<li>فعال ساختن داشبورد اختصاصی</li>
					<li>لیست داشبوردهای اختصاصی</li>
					<li>ایجاد داشبورد اختصاصی جدید</li>
					<li>ویرایش داشبورد اختصاصی</li>
					<li>حذف داشبورد اختصاصی</li>
				</ul>
			</li>
		</ul>
	</li>
	<li>مدیریت محتوا
		<ul>
			<li>متن
				<ul>
					<li>لیست متن‌ها</li>
					<li>ایجاد متن جدید</li>
					<li>ویرایش متن</li>
					<li>حذف متن</li>
				</ul>
			</li>
			<li>آلبوم
				<ul>
					<li>لیست آلبوم‌ها</li>
					<li>ایجاد آلبوم جدید</li>
					<li>ویرایش آلبوم</li>
					<li>حذف آلبوم</li>
				</ul>
			</li>
			<li>منو
				<ul>
					<li>لیست منو‌ها</li>
					<li>ایجاد منوی جدید</li>
					<li>ویرایش منو</li>
					<li>حذف منو</li>
				</ul>
			</li>
			<li>صفحه
				<ul>
					<li>لیست صفحات</li>
					<li>ایجاد صفحه جدید</li>
					<li>ویرایش صفحه</li>
					<li>حذف صفحه</li>
				</ul>
			</li>
			<li>سناریو
				<ul>
					<li>لیست سناریو‌ها</li>
					<li>ایجاد سناریوی جدید</li>
					<li>ویرایش سناریو</li>
					<li>حذف سناریو</li>
				</ul>
			</li>
			<li>پیوند
				<ul>
					<li>لیست پیوند‌ها</li>
					<li>ایجاد پیوند جدید</li>
					<li>ویرایش پیوند</li>
					<li>حذف پیوند</li>
				</ul>
			</li>
		</ul>
	</li>

	<li>مدیریت ابزار
		<ul>
			<li>ابزارهای عمومی
				<ul>
					<li></li>
				</ul>
			</li>
			<li>ابزارهای اختصاصی
				<ul>
					<li></li>
				</ul>
			</li>
			<li>قالب متن
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</li>

	<li>مدیریت کاربر
		<ul>
			<li>
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</li>

	<li>مدیریت پوسته ها
		<ul>
			<li>
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</li>

	<li>گزارشات
		<ul>
			<li>
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</li>

	<li>راهنما
		<ul>
			<li>
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</li>

	<li>خروج</li>
</ol>

						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
