<script type="text/javascript">
$(document).ready(function(){
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
	})
	chk();
	function chk(){	
		if ($('#chk_seprator').is(':checked'))
		{
			$("#link_url").hide("fast");
		}
		$('#chk_seprator').click(function ()
		{
			if ($('#chk_seprator').is(':checked'))
			{
				$("#link_url").hide("fast");
			}
			else
			{
				$("#link_url").show("fast");
			}
		});
	}
})

</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.td_title{width:100px;}.td_box{width:420px;}.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
		echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
		echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title_site); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

<!--<div id="div_tbl" class="ui-corner-all ui-widget-header"><center><h1><?php echo $this->escape($this->title_site);?></h1></center></div>
<div id="div_tbl" class="ui-corner-all ui-widget-content">--> 
	<form action="/dashboard/link/crt" method="post">
	<table style="width: 540px; margin: 0pt auto; text-align: right; direction:rtl;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('d');?></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="title" value="<?php echo $this->data['title']; ?>">
				</td>
			</tr>
			<tr title="<?php echo $this->translate->_('e');?>">
				<td class="td_title"><label class="label"><?php echo $this->translate->_('f');?> </label></td>
				<td class="td_box"><input type="checkbox" <?php if ($this->data['url']=='#'){echo 'checked="checked"';} ?> id="chk_seprator" name="chk_seprator"></td> 
			</tr>
			<tr id="link_url">
				<td class="td_title"><label class="label"><?php echo $this->translate->_('g');?> </label></td>
				<td class="td_box">
				<!--<div style="width:50%;float:right;">-->
				<input type="text" class="inputBox" size="35" maxlength="200" name="url" value="<?php echo $this->data['url']; ?>">
				<!--</div><div style="width:30%;float:right;direction: ltr;"><?php echo $this->translate->_('h');?></div>-->
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('user group');?></label></td>
				<td id="userGroups" class="td_box">
				<style>#userGroups div{<?php echo $this->translate->_('stylea'); ?>}</style>
				<?php
					$currentGroups	= array();
					if(!empty($this->data['user_group'])) $currentGroups	= array_filter(explode('/', $this->data['user_group']));
					if(is_array($this->wbsUserGroups))
						foreach($this->wbsUserGroups as $value)
						{
							$checkedState = '';
							if( in_array($value['id'],$currentGroups) ) $checkedState = 'checked="checked"';
							echo '<div><input type="checkbox" name="ugroup[]" value="'.$value['id'].'" '.$checkedState.' /><label>&nbsp;'.$value['title'].'</label></div>'; 
						}
				?>
					<div style="width:99.9%;float:left;"><br /><span style="font-size:90%;color:#0000CC;"><?php echo $this->translate->_('z');?></span><br /><br /></div>
				</td>
			</tr>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['id']; ?>" name="id" />
	</form>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#"><?php echo $this->translate->_('m');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/dashboard/link/frmlist#fragment-2" ><?php echo $this->translate->_('n');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
