<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  .click(function(){ $('#facebox #confirm').attr('href', '/dashboard/scenario/del/id/'+$(this).attr('val')); })
    })
</script>
<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;/*width:650px;border:1px solid;*/height:auto;}
.d1{width:5%;}.d2{width:23%;}.d3{width:22%;direction:ltr;text-align:left;}.d4{width:9%;}.d5{width:19%;}.d6{width:22%;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg){echo  "<h4>".$msg."</h4>";}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title_site); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<!--<div id="div_tbl" class="ui-corner-all ui-widget-header"><center><h1><?php echo $this->escape($this->title_site); ?></h1></center></div>
<div id="div_tbl" class="ui-corner-all ui-widget-content" > -->
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder ui-widget" style="table-layout:fixed;width:100%;">
			<tr  class="ui-widget-header" >
			  <th class="d1" ><?php echo $this->translate->_('b');?></th>  
			  <th class="d2" ><?php echo $this->translate->_('c');?></th>
			  <th class="d3" style="text-align:center;"><?php echo $this->translate->_('d');?></th>	  
			  <th class="d4" ><?php echo $this->translate->_('e');?></th>	  
			  <th class="d5" ><?php echo $this->translate->_('f');?></th>	
			  <th class="d6" ><?php echo $this->translate->_('g');?></th>	    
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr class="ui-widget-content">
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" ><?php echo $i['title'];?></td>
				<td class="d3" ><?php echo '<a href="'.$i['uri'].'" >YourSite'.$i['uri'].'</a>'; ?></td>
				<td class="d4" ><?php echo $i['page_id']; ?></td>
				<td class="d5" ><?php echo get_scro_action ($i['action_id'], $this->translate); ?></td>
				
				<td class="d6" >
					<a href="/dashboard/scenario/frmedit/id/<?php echo $i['id'];?>#fragment-2"><?php echo $this->translate->_('h');?></a>&nbsp;|&nbsp;
					<a href="/dashboard/scenario/updateallsubs/id/<?php echo $i['id'];?>" title="<?php echo $this->translate->_('r');?>"><?php echo $this->translate->_('q');?></a>&nbsp;|&nbsp;
					<a href="#dlg_scenario" class="sel_link" val="<?php echo $i['id'];?>" name="<?php echo $i['title'];?>" rel="facebox"><?php echo $this->translate->_('i');?></a>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,$this->BaseUrl(), $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('j');
		//echo paging($this->count,$this->start,$this->limit,$this->BaseUrl(),$this->env);
		
	}
?>

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/dashboard" ><?php echo $this->translate->_('k');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<div id="dlg_scenario" style="display:none;">
<?php echo $this->translate->_('o');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" ><?php echo $this->translate->_('m');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$('#facebox a.close').click();" ><?php echo $this->translate->_('n');?></a>
</span>
<br />
<br />
</div>
<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/dashboard/scenario/frmlist/st/".$back ."' class='btn ui-state-default ui-corner-all'><font  size='2'>"
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/dashboard/scenario/frmlist/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/dashboard/scenario/frmlist/st/".$this1."' class='btn ui-state-default ui-corner-all'><font  size='2'>"
								.  $translate->_('next page')."</font></a>";
					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
//---------------
function get_scro_action($id, $translate)
{
	switch ($id)
	{
		case 1: return $translate->_('p'); //'نمایش آخرین پست ها';
		case 2: return $translate->_('s');
	}
}
?>