<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script language="javascript" type="text/javascript" src="/ZrastakCMS/public/admin/public/js/10:13:53"></script>

<link rel="stylesheet" type="text/css" href="/ZrastakCMS/public/admin/public/css/10:11:12" />

<title>demo</title>
</head>

<body>

	<div class="demo">
		
		<div id="resizable" class="ui-widget-content">
			
		</div>
	
	</div>

</body>
</html>