<script type="text/javascript">
$(document).ready(function(){

	metaBlockInput("select[name='type']");
	$("select[name='type']").change(function(){ metaBlockInput(this); });
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
		return false;
	})
})
function metaBlockInput(elem)
{
		var type	= $(elem).val();
		var metaFld	= $('#form_container tr#meta_block');
		if(type=='h' && metaFld.length )
		{
			$('body').data('meta_block', [metaFld.find('select[name="meta_type"]').val(), metaFld.find('[name="meta_block"]').val()]);
			metaFld.fadeOut(100, function(){$(this).html('');});
			return;
		}
		else if(type!='h' && metaFld.find('select[name="meta_type"]').length==0)
		{
			var metavals	= $('body').data('meta_block');
			metaFld.html($('#null_metab_input tr#meta_block').html());
			metaFld.show();
			if(metavals.length)
			{
				metaFld.find('select[name="meta_type"]').val( metavals[0] );
				metaFld.find('[name="meta_block"]').val( metavals[1] );
			}
		}
}
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.td_title{width:100px;}.td_box{width:420px;}.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="<?php echo $this->form_action;?>" method="post">
	<table id="form_container" style="width: 840px; margin: 0pt auto; text-align: right; direction:<?php echo $this->translate->_('dir');?>;">
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('title');?></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="title" value="<?php echo $this->data['title']; ?>">
				</td>
			</tr>
			<tr>
				<td><label class="label"><?php echo $this->translate->_('type');?></label></td>
				<td class="td_box">
						<br /><select name="type">
							<option value="n" <?php if($this->data['type']=='n') echo 'selected="selected"'; ?>><?php echo $this->translate->_('normal');?> </option>
							<option value="q" <?php if($this->data['type']=='q') echo 'selected="selected"'; ?>><?php echo $this->translate->_('menu');?> </option>
							<option value="h" <?php if($this->data['type']=='h') echo 'selected="selected"'; ?>><?php echo $this->translate->_('s');?> </option>
							<option value="m" <?php if($this->data['type']=='m') echo 'selected="selected"'; ?>><?php echo $this->translate->_('m');?> </option>
						</select><br /><br />

				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('ae');?> </label></td>
				<td class="td_box">
					<textarea cols="80" rows="10" dir="ltr" name="block"><?php echo htmlspecialchars( stripslashes($this->data['block']) ); ?></textarea>
				</td> 
			</tr>
			<tr id="meta_block">
				<td class="td_title"><label class="label"><?php echo $this->translate->_('af');?> </label></td>
				<td class="td_box">
					<br /><select name="meta_type">
						<option value="1" <?php if($this->data['meta_type']=='1') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ag');?> </option>
						<option value="2" <?php if($this->data['meta_type']=='2') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ah');?> </option>
						<option value="3" <?php if($this->data['meta_type']=='3') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ai');?> </option>
					</select><br /><br />
					<textarea cols="80" rows="10" dir="ltr" name="meta_block"><?php echo htmlspecialchars( stripslashes($this->data['meta_block']) ); ?></textarea>
				</td> 
			</tr>
	</table>
	<input type="hidden" value="<?php echo $this->data['bid']; ?>" name="bid" />
	</form>
			

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#"><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/skiner/block/frmlist#fragment-4" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
<table id="null_metab_input" style="display:none;">
	<tr id="meta_block">
		<td class="td_title"><label class="label"><?php echo $this->translate->_('af');?> </label></td>
		<td class="td_box">
			<br /><select name="meta_type">
				<option value="1" <?php if($this->data['meta_type']=='1') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ag');?> </option>
				<option value="2" <?php if($this->data['meta_type']=='2') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ah');?> </option>
				<option value="3" <?php if($this->data['meta_type']=='3') echo 'selected="selected"'; ?>><?php echo $this->translate->_('ai');?> </option>
			</select><br /><br />
			<textarea cols="80" rows="10" dir="ltr" name="meta_block"><?php echo htmlspecialchars( stripslashes($this->data['meta_block']) ); ?></textarea>
		</td> 
	</tr>
</table>
