<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en"  style="overflow:scroll;">
<head>
	<link rel="icon" type="image/gif" href="/img/RSDFavIconlogo.gif" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<title><?php echo $this->title_site; ?></title>
	<?php echo $this->pageHead;?>
</head>
<body>
	<?php echo $this->layout()->content ?>
	<?php if( defined('ADS') ) echo ADS ?>
</body>
</html>

