<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en"  style="overflow:scroll;">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	
	<?php echo $this->pageHead;?>
</head>
<body>
<?php
	 if(isset($_GET['mdi']))
	 	echo $this->mDashboard($_GET['mdi']);
	 elseif(isset($_SESSION['MyApp']['mdi']))
	 	echo $this->mDashboard($_SESSION['MyApp']['mdi']);
 ?>
	<?php echo $this->layout()->content ?>
	<?php if( defined('ADS') ) echo ADS ?>
</body>
</html>

