<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="overflow:scroll;">
<head>
	<link rel="icon" type="image/gif" href="/img/RSDFavIconlogo.gif" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
	<link type="text/css" rel="stylesheet" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/rasta/controlpanel.css" />

	<script type="text/javascript" src="/js/jQuery/jquery.js"></script>
	<title><?php echo $this->translate->_('ga') . $this->escape($this->title_site); ?></title>

<script type="text/javascript">
$(function(){
$('.art-button-wrapper').live('hover', function(){$(this).toggleClass('hover');});

$('.alert-col').slideDown();

//text box code	
	$(":input[@type=text]").focus(function(){
		$(this).css('border','1px solid #6699FF');
	});
	$(":input[@type=text]").blur(function(){
		$(this).css('border','1px solid silver');
	});
//end text box code
})

function showAlertColFirst()
{
if($('.alert-col').is(':animated')) $('.alert-col').stop(true, true).hide();
else if($('.alert-col').is(':visible')) $('.alert-col').stop(true, true);
$('.alert-col-btm').hide();$('.alert-col').show(1000).fadeTo(500, 0.87).delay(12000).hide(1000, function(){$('.alert-col-btm').show(500);})
}
function showAlertCol()
{
$('.alert-col-btm').hide();$('.alert-col').show(1000).fadeTo(500, 0.87);
}

function hideAlertCol()
{
$('.alert-col').hide(1000, function(){$('.alert-col-btm').show(500);})
}
function callAlertCol(msg)
{
	if($('.alert-col').length)
	{
		$('.alert-col').html(msg)
		showAlertColFirst();
	}
	else
	{
		var htmls	= '<div class="alert-col" onclick="hideAlertCol();">'+msg+'</div><div class="alert-col-btm" onclick="showAlertCol()"><?php echo $this->translate->_('gb'); ?></div>';
		$('#container').before(htmls);
		showAlertColFirst();
	}
}

</script>
<style type="text/css" media="screen">
body{
background-image:url("/modules/rcpanel/images/bggrad.jpg");
}
body, div, span, a, p{font-family:tahoma;font-size:12px;text-decoration:none;line-height:1.5;}
.nav-bar{width:98%;height:20px;position:absolute;top:0;left:0;background:url("/modules/rcpanel/images/menubar1.jpg") repeat-x;padding:7px 1%;
color:#FFFFFF;text-align:right;min-width:850px;
}
.nav-bar a{color:#FFFFFF;}
.nav-bar-left{width:200px;height:20px;position:absolute;top:0;left:0;padding:7px 20px;text-align:left;z-index:12;
}
.nav-bar-right{width:auto;height:20px;position:absolute;top:0;right:0px;padding:7px 20px;text-align:right;z-index:12;
}
.nav-bar-center{width:94px;height:20px;position:absolute;top:0;left:48%;padding:2px 3px;text-align:center;z-index:12;
background: url("/modules/rcpanel/images/bgloading.png")  no-repeat;font-size:10px;
}



#art-page-background-simple-gradient, #art-page-background-gradient, #art-page-background-glare {
    min-width: 900px;
}
#art-page-background-glare {
    height: 388px;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
	z-index: 10;
}
#art-page-background-glare-image {
    background-image: url("/modules/rcpanel/images/page_gl.png");
    background-repeat: no-repeat;
    height: 388px;
    margin: 0 auto;
    width: 1086px;
}

#container{width:900px;height:auto;float:none;margin:0 auto;position:relative;z-index:20;top:35px;}
#container page{ width:100%;}
.alert-col, .alert-col-btm{width:200px;height:auto;position:absolute;top:34px;left:0px;padding:15px;display:none;
background-color:#000000;word-wrap: break-word;color:#ff0000;text-align:right;direction:rtl;z-index:22;
}
.alert-col-btm{width:70px;font-size:10px;padding:2px;cursor:pointer;}


/* begin Button */
.art-button-wrapper .art-button
{

  display: inline-block;
  vertical-align: middle;
  white-space: nowrap;
  text-align: left;
  text-decoration: none !important;
  color: #000000 !important;
  width: auto;
  outline: none;
  border: none;
  background: none;
  line-height: 32px;
  height: 32px;
  margin: 0;
  padding: 0 19px !important;
  overflow: visible;
  cursor: default;
  z-index: 0;
}

.art-button img, .art-button-wrapper img
{
  margin: 0;
  vertical-align: middle;
}

.art-button-wrapper
{
  vertical-align: middle;
  display: inline-block;
  position: relative;
  height: 32px;
  overflow: hidden;
  white-space: nowrap;
  width: auto;
  margin: 0;
  padding: 0;
  z-index: 0;
}

.firefox2 .art-button-wrapper
{
  display: block;
  float: left;
}

input, select, textarea, select
{
  vertical-align: middle;

}

.art-block select 
{
    width:96%;
}

.art-button-wrapper.hover .art-button, .art-button:hover
{
  color: #F0F7F9 !important;
  text-decoration: none !important;
}

.art-button-wrapper.active .art-button
{
  color: #EFF4F6 !important;
}

.art-button-wrapper .l, .art-button-wrapper .r
{
  display: block;
  position: absolute;
  z-index: -1;
  height: 96px;
  margin: 0;
  padding: 0;
  background-image: url('/modules/rcpanel/images/button.png');
}

.art-button-wrapper .l
{
  left: 0;
  right: 9px;
}

.art-button-wrapper .r
{
  width: 411px;
  right: 0;
  clip: rect(auto, auto, auto, 402px);
}

.art-button-wrapper.hover .l, .art-button-wrapper.hover .r
{
  top: -32px;
}

.art-button-wrapper.active .l, .art-button-wrapper.active .r
{
  top: -64px;
}

.art-button-wrapper input
{
  float: none !important;
}
/* end Button */

</style>
</head>
<body>
<div id="art-page-background-glare">
        <div id="art-page-background-glare-image"></div>
    </div>
<div class="nav-bar">
	<div class="nav-bar-right">
<?php
	if(defined('USRiD'))
	{
		$registry	= Zend_registry::getInstance();
		$DB	= $registry['front_db'];
		$sql	='select count(*) from `wbs_profile` where `host_id`='.$this->user_id;
		$has_wbs= $DB->fetchOne($sql);
		if ($has_wbs==0)
		{?>
			&nbsp;&nbsp;<a href="/rcpanel/panel/"><?php echo $this->translate->_('gc'); ?></a>&nbsp;&nbsp;|
			&nbsp;&nbsp;<a href="/rcpanel/panel/frmcrtsite"	><?php echo $this->translate->_('gd'); ?></a>&nbsp;&nbsp;
<?php	}
		else if ($has_wbs==1)
		{?>
			&nbsp;&nbsp;<a href="/rcpanel/panel/"><?php echo $this->translate->_('gc'); ?></a>&nbsp;&nbsp;|
			<!--&nbsp;&nbsp;<a href="#"><?php echo $this->translate->_('ge'); ?></a>&nbsp;&nbsp;|-->
			&nbsp;&nbsp;<a href="/rcpanel/panel/frmparkdomain"><?php echo $this->translate->_('gg'); ?></a>&nbsp;&nbsp;|
			&nbsp;&nbsp;<a href="/rcpanel/export/frmwordpress"><?php echo $this->translate->_('gf'); ?></a>&nbsp;&nbsp;
<?php	} 
	} ?>
	</div>
	<div class="nav-bar-center" id="loading" style="display:none;">
	<span dir="rtl"><?php echo $this->translate->_('gh'); ?></span>
	</div>
	<div class="nav-bar-left">
<?php
	if(defined('USRiD'))
	{ ?>
		<a href="/rcpanel/user/frmedit"><?php echo $this->translate->_('gi'); ?></a>&nbsp;&nbsp;|
		<a href="/rcpanel/user/logout"><?php echo $this->translate->_('gj'); ?></a>&nbsp;&nbsp;
<?php 
	}else{ ?>
		<a href="/rcpanel/user/frmreguser"><?php echo $this->translate->_('gk'); ?></a>&nbsp;&nbsp;|
		<a href="/rcpanel/user/frmlogin"><?php echo $this->translate->_('gl'); ?></a>&nbsp;&nbsp;
<?php 
	} ?>
	</div>
</div>
<?php if(!empty($this->msg) and is_array($this->msg)):?>					
	<div class="alert-col" onclick="hideAlertCol();">
	<?php foreach($this->msg as $msg) echo $msg.'<br />'; ?>					
	</div>
	<div class="alert-col-btm" onclick="showAlertCol()"><?php echo $this->translate->_('gb'); ?></div>					
	<script>$(function(){showAlertColFirst();})</script>
<?php endif; ?>	

	<div id="container" >
		<div id="main_section" >
			<div id="content">
				<?php 
					echo $this->layout()->content ;
					echo $this->layout()->registeruser;	
				?>
			</div>
		</div>
	</div>
</body>
</html>