<script type="text/javascript">
//--------------------------
$(document).ready(function() {
		$("li").removeClass("ui-state-active");
		$("#tb_editsite").addClass("ui-state-active");
})
function submitForm()
{
	document.forms[0].submit();
}

</script>

<style>
.td_title{width:100px;}.td_box{	width:420px;}#div_tbl{margin:0 auto;padding:10px;margin-top:5px;width:650px;border:1px solid;height:auto;}
</style>
  	<?php 
		if (!empty($this->msg))
		{
			echo '<div class="ui-state-error ui-corner-all"	>';
			foreach ($this->msg as $msg)
  			{echo "<h2>".$msg."</h2>";}
			echo '</div>';
		}
	?>

	<div id="div_tbl" class="ui-corner-all ui-widget-header"><center><h1><?php echo $this->escape($this->title);?></h1></center></div>
	<div id="div_tbl" class="ui-corner-all ui-widget-content" >
	<form method="post" action="<?php echo $this->baseUrl(); ?>/rcpanel/panel/editsite">
		<input type="hidden" name="id" value="<?php echo $this->data['wb_id']; ?>">
		<table style="width:540px; margin:0 auto;text-align:right;">
			<tr title="عنوان سایت شما در تمامی صفحاتی که خاصیت راست به چپ دارند نمایش گذاشته خواهد شد">
				<td class="td_title"><label class="label">عنوان سایت:* </label></td>
				<td class="td_box"><input type="text" name="s_title" maxlength="100" size="35" class="inputBox"  value="<?php echo $this->data['wb_title']; ?>"> </td>
			</tr>
			
		<tr title="عنوان لاتین سایت شما در صورت استفاده از خاصیت چپ به راست به نمایش در خواهد آمد">
			<td class="td_title"><label class="label">عنوان لاتین سایت: </label></td>
			<td class="td_box"><input type="text" name="s_latintitle" maxlength="100" size="35" class="inputBox"  value="<?php echo $this->data['latin_title']; ?>"> </td>
		</tr>
			
			
			<tr title="شعار مربوط به سایت شما می باشد">
				<td class="td_title"><label class="label">شعار سایت: </label></td>
				<td class="td_box"><textarea name="s_slogan" size="35"  rows="2" cols="32" class="inputBox"><?php echo $this->data['wb_slogan']; ?></textarea></td> 
			</tr>
			<tr title="در صورت تمایل می توانید نام موِلّفان سایت خود را ذکر کنید">
				<td class="td_title"><label class="label">نویسندگان سایت: </label></td>
				<td class="td_box"><textarea name="s_authors" size="35"  rows="2" cols="32" class="inputBox"><?php echo $this->data['wb_authors']; ?></textarea></td>
			</tr>
			<tr title="این توضیحات جهت ارائه به موتور های جستجو می باشد">
				<td class="td_title"><label class="label">توضیحات: </label></td>
				<td class="td_box"><textarea name="s_description" size="35"  rows="2" cols="32" class="inputBox"><?php echo $this->data['wb_description']; ?></textarea></td>
			</tr>
			<tr title="کلمات کلیدی دسترسی افراد مختلف را از طریق موتور جستجو به سایت شما آسان می کند">
				<td class="td_title"><label class="label">کلمات کلیدی: </label></td>
				<td class="td_box"><textarea name="s_keywords" size="35"  rows="2" cols="32" class="inputBox"><?php echo $this->data['wb_keywords']; ?></textarea></td> 
			</tr>
	
			
		</table>
	</div>
	<div id="div_tbl" class="ui-corner-all ui-state-highlight">
	<center>
		<a  class='btn ui-state-default ui-corner-all' href="#"	onclick="javascript :submitForm();" >تایید</a>
		<a  class='btn ui-state-default ui-corner-all' href="/rcpanel/panel/" >انصراف</a>
	</center>
	</div>