<chart>
	<axis_category shadow='low' />
	<axis_value shadow='low' min='0' size='10' alpha='50' steps='4' />
	
	<chart_border color='000000' top_thickness='1' bottom_thickness='2' left_thickness='0' right_thickness='0' />
	<chart_data>
		<row>
			<null/>
			<string>Rich Text</string>
			<string>Gallery</string>
			<string>Menu</string>
			<string>Page</string>
			<string>Scenario</string>
			<string>External Link</string>
		</row>
		<row>
			<string></string>
			<number bevel='blue' shadow='high'><?php echo $this->data['rtc']; ?></number>
			<number bevel='blue' shadow='high'><?php echo $this->data['gallery']; ?></number>
			<number bevel='blue' shadow='high'><?php echo $this->data['menu']; ?></number>
			<number bevel='blue' shadow='high'><?php echo $this->data['page']; ?></number>
			<number bevel='blue' shadow='high'><?php echo $this->data['scenario']; ?></number>
			<number bevel='blue' shadow='high'><?php echo $this->data['extlink']; ?></number>
		</row>
	</chart_data>
	<chart_grid_h alpha='10' thickness='1' type='dashed' />
	<chart_label color='ddffff' alpha='90' size='10' position='middle' />
	<chart_note type='arrow' size='13' color='000000' alpha='75' x='-10' y='-30' background_color_1='FF4400' background_alpha='75' shadow='low' />
	<chart_rect bevel='bg' shadow='high' x='10' y='100' width='620' height='200' positive_color='eeeeff' negative_color='dddddd' positive_alpha='100' negative_alpha='100'  corner_tl='0' corner_tr='0' corner_br='40' corner_bl='40' />
	<chart_transition type='scale' delay='.5' duration='1' order='series' />

	<draw>
		<text shadow='high' transition='dissolve' delay='0' duration='0.5' alpha='20' size='48' x='8' y='8' width='400' height='75' h_align='left' v_align='bottom'>Site Contents</text>
		<?php /*?><text shadow='high' color='f8f8ff' alpha='50' rotation='-90' size='75' x='-20' y='300' width='300' height='200' h_align='center'>revenue</text>
		<text shadow='low' color='000033' alpha='50' rotation='-90' size='16' x='7' y='230' width='300' height='50' h_align='center' v_align='middle'>(millions)</text><?php */?>
	</draw>
	<filter>
		<shadow id='high' distance='5' angle='45' alpha='35' blurX='10' blurY='10' />
		<bevel id='bg' angle='45' blurX='50' blurY='50' distance='10' highlightAlpha='50' highlightColor='ffffff' shadowAlpha='10' inner='true' />
		<bevel id='blue' angle='-80' blurX='0' blurY='30' distance='20' highlightColor='ffffff' highlightAlpha='50' shadowColor='000088' shadowAlpha='25' inner='true' />
	</filter>
	
	<legend layout="hide" />

	<series_color>
		<color>768bb3</color>
	</series_color>
	<series set_gap='40' />
	
</chart>

