<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($){
      $('a[rel*=facebox]').facebox({
        loadingImage : '/lib/facebox/v2/loading.gif',
        closeImage   : '/lib/facebox/v2/closelabel.png'
      });
    })
function pageSelectConfirm()
{
			if ($('input:radio[name=rdo]:checked').val())
			{
				$('input[name=s_page_id]').val($('input:radio[name=rdo]:checked').val());
				$('#facebox a.close').click();
			}
			else	alert('<?php echo $this->translate->_('b');?>');
			return false;	  
}
</script>
<style>
.td_title{width:100px;}.td_box{width:420px;}.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
.ppr{width:250px;}
.pp1{width:30px;}
.pp2{width:200px;}
.btn{margin:3px;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title_site); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="/taxonomy/registration/edit" method="post">
	<table style="width: 540px; margin: 0pt auto; text-align: right; direction:rtl;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('c');?></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="200" name="s_title" value="<?php echo $this->data['title']; ?>">
				</td>
			</tr>			
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('d');?></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="200" name="s_name" value="<?php echo $this->data['name']; ?>">
				</td>
			</tr>
			
			<?php if(is_array($this->whs_tterms)){ ?>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('t');?> </label></td>
				<td class="td_box">
					<?php
					$subscens	= false;
					if(!empty($this->data['first_subs']))	$subscens	= array_filter( explode('/', $this->data['first_subs']) );

					foreach($this->whs_tterms as $scen)
					{
						$chk	= '';
						if($subscens)	if(in_array($scen['id'],$subscens)) $chk	= 'checked="checked"';
						echo '<div class="sub_b"><input type="checkbox" name="subscens['.$scen['id'].']" id="sub_'.$scen['id'].'" '.$chk.' /><label for="sub_'
							. $scen['id'].'">'.$scen['title'].'</label></div>';
					}
					
					?>
					<style><?php $rorl	= ($this->translate->_('dir')=='rtl')?'right':'left'; ?>
					.sub_b{width:48%;height:20px;overflow:hidden;float:<?php echo $rorl; ?>;text-align:<?php echo $rorl; ?>;}</style>
				</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['id']; ?>" name="id" />
	</form>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#" onclick="document.forms[0].submit();"><?php echo $this->translate->_('m');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/taxonomy/list#fragment-2" ><?php echo $this->translate->_('n');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

