<script src="/charts/AC_RunActiveContent.js" language="javascript"></script>
<script language="JavaScript" type="text/javascript">
<!--
function getChart(source, width, height)
{
	var requiredMajorVersion = 10;
	var requiredMinorVersion = 0;
	var requiredRevision = 45;

if (AC_FL_RunContent == 0 || DetectFlashVer == 0) {
	alert("This page requires AC_RunActiveContent.js.");
} else {
	var hasRightVersion = DetectFlashVer(requiredMajorVersion, requiredMinorVersion, requiredRevision);
	if(hasRightVersion) { 
		AC_FL_RunContent(
			'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,45,2',
			'width', width,
			'height', height,
			'scale', 'noscale',
			'salign', 'TL',
			//'bgcolor', '#cccccc',
			'wmode', 'opaque',
			'movie', 'charts',
			'src', '/charts/charts',
			'FlashVars', 'library_path=/charts/charts_library&xml_source='+source, 
			'id', 'my_chart',
			'name', 'my_chart',
			'menu', 'true',
			'allowFullScreen', 'true',
			'allowScriptAccess','sameDomain',
			'quality', 'high',
			'align', 'middle',
			'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
			'play', 'true',
			'devicefont', 'false'
			); 
	} else { 
		var alternateContent = 'This content requires the Adobe Flash Player. '
		+ '<u><a href=http://www.macromedia.com/go/getflash/>Get Flash</a></u>.';
		document.write(alternateContent); 
	}
}
}
// -->
</script>
<?php if($this->rep=='all' or $this->rep=='visits'){ ?>
<div>
<script language="JavaScript" type="text/javascript">getChart('/stat/data/visits', '950', '450');</script>
</div>
<?php } ?>
<?php if($this->rep=='all' or $this->rep=='visitors'){ ?>
<div>
<script language="JavaScript" type="text/javascript">getChart('/stat/data/visitors', '950', '450');</script>
</div>
<?php } ?>
<?php if($this->rep=='all' or $this->rep=='activeusers'){ ?>
<div>
<script language="JavaScript" type="text/javascript">getChart('/stat/data/activeusers', '450', '450');</script>
</div>
<?php } ?>
<?php if($this->rep=='all' or $this->rep=='sitecontents'){ ?>
<div>
<script language="JavaScript" type="text/javascript">getChart('/stat/data/sitecontents', '650', '450');</script>
</div>
<?php } ?>
