<script type="text/javascript">
$(document).ready(function(){
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
		return false;
	})
})
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.inputBox{text-align:left;direction:ltr;}

.td_title{width:100px;text-transform:uppercase;}
.td_box{width:420px;}
.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
select.lay_select{width:200px;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader" style="text-transform:capitalize;"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="<?php echo $this->form_action;?>" method="post">
	<table style="width: 820px; margin: 0pt auto; text-align: right; direction:ltr;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('Name');?>&nbsp;<font color="#FF0000">*</font></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="name" value="<?php echo $this->data['name']; ?>">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ai');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('layout');?></label></td>
				<td class="td_box" dir="ltr">
<?php
 if(is_array($this->wbs_layouts))
{
	echo '<select name="layout" class="lay_select">';
		echo '<option value="0">&nbsp;&nbsp;&nbsp;&nbsp;</option>';
	foreach($this->wbs_layouts as $ly) 
		echo '<option value="'.$ly['ly_id'].'" '.(($ly['ly_id']==$this->data['layout'])?'selected="selected"':'').'>'.
			(($ly['wbs_id']==0)?'Public:':'Dedicated:').'&nbsp;&nbsp;'.$ly['ly_title'].'&nbsp;&nbsp;</option>';
	echo '</select>';
}
 ?>
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('comment');?> </label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="100" maxlength="300" name="comment" value="<?php echo $this->data['comment']; ?>">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ah');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('init');?> </label></td>
				<td class="td_box"><br />
					<textarea cols="75" rows="10" dir="ltr" name="init"><?php echo htmlspecialchars($this->data['init']); ?></textarea>
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;"><?php echo $this->translate->_('aj');?></span><br /><br />
				</td> 
			</tr>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['pid']; ?>" name="pid" />
	<input type="hidden" value="<?php echo $this->data['cid']; ?>" name="cid" />
	</form>
			

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="#" onclick="document.forms[0].submit();return false;"><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/portlet/management/frmlist#fragment-3" ><?php echo $this->translate->_('cancel');?></a>
</span>
<?php if(is_numeric($this->data['cid'])){ ?>
<span class="art-button-wrapper " style="text-transform:capitalize;">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="#dlg_acform" rel="facebox" ><?php echo $this->translate->_('add new action');?></a>
</span>
<?php } ?>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
<style>
pre {
    direction:ltr;
	border: 1px solid #CCCCCC;
    margin: 13px auto;
    overflow: auto;
    padding: 10px;
    width: 95%;
}
pre.cr_ac_comment {
	color:#666666;
}
pre.cr_ac_code {
	color:#0000EE;
	text-align:left;
	border-color:#009900;
}
span.opr{
	cursor:pointer;
}
</style>
<script>
function acedit(elem){
	var ac	= $(elem).parents('.cr_ac_block').attr('unic');
	getAction(ac, helper_fillform);
}
function acdel(elem){
	if(elem=='confirm')
	{
		$.facebox.close();
		return delAction($('#facebox').data('acid'), helper_del_block );
	}
	var ac	= $(elem).parents('.cr_ac_block').attr('unic');
	$('#facebox').data('acid', ac);
}
function actogg(elem){
	var ne	= $(elem).parents('.cr_ac_block');
	if( ne.find('.ac_container:visible').length )
	{
		ne.find('.ac_container').hide();
		ne.find('.opr_toggle').text('expand');
		return;
	}
	ne.find('.ac_container').show();
	ne.find('.opr_toggle').text('collapse');
}
function acrun(elem){
	var ac	= $(elem).parents('.cr_ac_block').attr('unic');
	window.location	= '/portlet/management/runaction/id/'+ac;
}
function getAction(ID, sufn ){
	if(! /^\d+$/.test(ID) )	return false;
	$.ajax({
		url: "/portlet/management/getactiondata",
		dataType: "json",
		data: {acid:ID, crid:<?php echo $this->data['cid']; ?> },
		success: sufn
			});
}
function delAction(ID, sufn ){
	if(! /^\d+$/.test(ID) )	return false;
	$.ajax({
		url: "/portlet/management/delaction",
		dataType: "json",
		data: {acid:ID, crid:<?php echo $this->data['cid']; ?> },
		success: sufn
			});
}
function helper_fillform(data){
		if(data.state=='true')
		{
			$('[href="#dlg_acform"][rel="facebox"]').click();
			var ielm = $('#facebox #frm_acform input');
			for( name in data.data )
				if( ielm.filter('[name="'+name+'"]').length ) ielm.filter('[name="'+name+'"]').val(data.data[name]);
			$('#facebox #frm_acform textarea[name="accode"]').val(data.data.accode);
			$('#facebox #frm_acform select[name="aclayout"]').val(data.data.aclayout);
		}
		else	alert(data.msg);
}
function helper_refresh_block(data){
		if(data.state=='true')
		{
			var elem	= $('.cr_ac_block[unic="'+data.data.aid+'"]');
			if(!elem.length)
			{
				var htm	= '<div class="art-post cr_ac_block" unic="'+data.data.aid+'" lay="'+data.data.aclayout+'">'
//				if( $('.cr_ac_block').length )
//				{
//					$('div#content').append(htm+$('.cr_ac_block').eq(0).html()+'</div>');
//					var elem	= $('.cr_ac_block[unic="'+data.data.aid+'"]');
//				}
//				else
//				{
					$('div#content').append(htm+$('#dlg_acform .art-post').eq(0).html()+'</div>');
					var elem	= $('.cr_ac_block[unic="'+data.data.aid+'"]');
					var elemh	= elem.find('span.art-postheader');
					elemh.html('<?php echo $this->translate->_('action'); ?>::<span class="cr_ac_name"></span>');
					htm	= '<span style="font-size:12px;">&nbsp;&nbsp;&nbsp;[<span class="opr opr_edit" style="color:#009900;" onclick="acedit(this);">edit</span>]'
						+ '&nbsp;&nbsp;&nbsp;[<span class="opr opr_delete" style="color:#009900;" onclick="acdel(this);">delete</span>]&nbsp;&nbsp;&nbsp;'
						+ '[<span class="opr opr_toggle" style="color:#009900;" onclick="actogg(this);">expand</span>]</span>';
					elemh.after(htm);
//				}
				elem.find('div.art-postcontent').addClass('ac_container');
			}
			elem.attr('lay', data.data.aclayout);
			elem.find('span.cr_ac_name').text(data.data.acname);
			elem.find('div.ac_container').html('');
			if(! /^\s*$/.test(data.data.accomment) )
				elem.find('div.ac_container').append($('<pre class="cr_ac_comment"></pre>').text('<!-- '+data.data.accomment+' -->') );
			if(! /^\s*$/.test(data.data.accode) )
				elem.find('div.ac_container').append( $('<pre class="cr_ac_code"></pre>').text(data.data.accode) );
			else
				elem.find('div.ac_container').append('<h3 style="color:#0033CC;">EMPTY</h3>');
		}
		else	alert(data.msg);
}
function helper_del_block(data){
		alert(data.msg);
		if(data.state=='true')
			$('.cr_ac_block[unic="'+data.aid+'"]').fadeOut('slow', function() { $(this).remove(); });
}
function delActionBlock(aid){
	getAction()
}
function regAction(){
	var ielm = $('#facebox #frm_acform input');
	dTr	= {accode: $('#facebox #frm_acform textarea[name="accode"]').val(), aclayout: $('#facebox #frm_acform select[name="aclayout"]').val() };
	for(i=0; i<ielm.length; i++)	dTr[ ielm.eq(i).attr('name') ] = (ielm.eq(i).attr('type')=='checkbox')?ielm.eq(i).is(':checked'):ielm.eq(i).val();
	var act	= (dTr.aid==0)?'crtaction':'editaction';
	$.ajax({
		url: "/portlet/management/"+act,
		dataType: "json",
		data: dTr,
		success: function( data ){
					alert(data.msg);
					if(data.state=='true')
					{
						$.facebox.close();
						getAction(data.aid, helper_refresh_block);
					}
				}
			});
}
</script>
<?php 
if(is_array($this->cr_ac))
	foreach($this->cr_ac as $ac)
	{
?>
	<div class="art-post cr_ac_block" unic="<?php echo $ac['ac_id'] ?>" lay="<?php echo $ac['ac_layout'] ?>">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader" style="text-align:center;direction:ltr;">
						<span class="art-postheader" style="text-transform:capitalize;">
						<?php echo $this->translate->_('action').'::<span class="cr_ac_name">'
						.htmlspecialchars($ac['ac_name']);?>
						</span></span>
							<span style="font-size:12px;">
								&nbsp;&nbsp;&nbsp;[<span class="opr opr_edit" style="color:#009900;" onclick="acedit(this);">edit</span>]
								&nbsp;&nbsp;&nbsp;[<a href="#dlg_alert" rel="facebox"><span class="opr opr_delete" style="color:#009900;" onclick="acdel(this);">delete</span></a>]
								&nbsp;&nbsp;&nbsp;[<span class="opr opr_toggle" style="color:#009900;" onclick="actogg(this);">expand</span>]
								&nbsp;&nbsp;&nbsp;[<span class="opr opr_toggle" style="color:#009900;" onclick="acrun(this);">run</span>]
							</span>
						</h2>
					</div>
					<div class="art-postcontent ac_container" style="display:none;">
						<!-- article-content -->
						<?php 
						if(!empty($ac['ac_comment'])) echo '<pre class="cr_ac_comment">&lt;!-- '.htmlspecialchars($ac['ac_comment']).' --&gt;</pre>';

						if(!empty($ac['ac_code'])) echo '<pre class="cr_ac_code">'. htmlspecialchars($ac['ac_code']).'</pre>';
						else
							echo '<h3 style="color:#0033CC;">EMPTY</h3>';
						?>
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

<?php 
	
	}
?>

<?php if(is_numeric($this->data['cid'])){ ?>

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()  })
</script>

<div id="dlg_acform" style="display:none;">

<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader" style="text-align:center;direction:ltr;">
							<span class="art-postheader" style="text-transform:capitalize;"><?php echo $this->translate->_('action');?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<form action="<?php echo $this->form2_action;?>" method="post" id="frm_acform">
	<table style="width: 820px; margin: 0pt auto; text-align: right; direction:ltr;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('Name');?>&nbsp;<font color="#FF0000">*</font></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="acname" value="">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ai');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('layout');?></label></td>
				<td class="td_box" dir="ltr">
<?php
 if(is_array($this->wbs_layouts))
{
	echo '<select name="aclayout" class="lay_select">';
		echo '<option value="0">&nbsp;&nbsp;&nbsp;&nbsp;</option>';
	foreach($this->wbs_layouts as $ly) 
		echo '<option value="'.$ly['ly_id'].'">'.
			(($ly['wbs_id']==0)?'Public:':'Dedicated:').'&nbsp;&nbsp;'.$ly['ly_title'].'&nbsp;&nbsp;</option>';
	echo '</select>';
}
 ?>
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('comment');?> </label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="100" maxlength="300" name="accomment" value="">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ah');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('scripts');?> </label></td>
				<td class="td_box"><br />
					<textarea cols="75" rows="10" dir="ltr" name="accode"></textarea>
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;"><?php echo $this->translate->_('ak');?></span><br /><br />
				</td> 
			</tr>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['pid']; ?>" name="pid" />
	<input type="hidden" value="<?php echo $this->data['cid']; ?>" name="cid" />
	<input type="hidden" value="0" name="aid" />
	</form>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="#" onclick="regAction();return false;"><?php echo $this->translate->_('ok');?></a>
</span>

<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$.facebox.close();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

</div>

<div id="dlg_alert" style="display:none;">
<?php echo $this->translate->_('an');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" onclick="acdel('confirm');return false;" ><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$.facebox.close();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
</div>

<?php } ?>

	
			

<!--<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/portlet/management/frmlist#fragment-3" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />-->

