<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  //.click(function(){ $('#facebox #confirm').attr('href', '/portlet/management/delportlet/id/'+$(this).attr('val')); })
    })
function delEntry(elem, type)
{
	if(elem=='confirm')
	{
		var ac	= $('#facebox').data('acid');
		if(! /^\d+$/.test(ac) &&  typeof ac != 'object')	return false;
		$.facebox.close();
		window.location	= (type=='pr')?'/portlet/management/delportlet/id/'+ac :'/portlet/management/delcontroller/prid/'+ac[0]+'/id/'+ac[1];
		return;
	}
	var ac	= (type=='pr')?$(elem).attr('val'):[$(elem).attr('pr'),$(elem).attr('cr')];
	$('#facebox').data('acid', ac);
}
</script>
<style>
th{text-transform:capitalize;}

#div_tbl{margin:0 auto;padding:10px;margin-top:2px;/*width:650px;border:1px solid;*/height:auto;}
.d1{width:5%;} td.d2{width:15%; text-align:center;}.d3{width:10%;}td.d4{width:30%;} .d5{width:30%;} .d6{width:10%;}

</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader" style="text-transform:capitalize;"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
<?php 
	if (count($this->data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder" style="width:100%;direction:ltr;">
			<tr >
			  <th class="d1" ><?php echo $this->translate->_('row');?></th>  
			  <th class="d2" ><?php echo $this->translate->_('portlet name');?></th>
			  <th class="d3" ><?php echo $this->translate->_('owner');?></th>	  
			  <th class="d4" ><?php echo $this->translate->_('controllers');?></th>	  
			  <th class="d5" ><?php echo $this->translate->_('comment');?></th>	  
			  <th class="d6" ><?php echo $this->translate->_('management');?></th>	  
			</tr>
		<?php 		
			
			$j=1;
			foreach($this->data as $i)
			{		
		?>
			<tr>
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" ><?php echo $i['pr_name'];	?></td>
				<td class="d3" ><?php echo ( ($i['wbs_id']==0)?'Public':'Dedicated'); ?></td>
				<td class="d4" >
				<?php 
					if( is_array($i['pr_cr']) )
					{
						echo '<table border="0" cellspacing="0" style="width:100%;direction:ltr;">';
						$crr	= 1;
						foreach($i['pr_cr'] as $cr)
						{
							if($cr['cr_wbs']==0)
							echo '<tr><td>'.$crr.'</td><td>'.$cr['cr_name'].'</td></tr>';
							else
							echo '<tr><td>'.$crr.'</td><td>'.$cr['cr_name']
							.'&nbsp;&nbsp;[<a href="/portlet/management/frmcontroller/prid/'.$i['pr_id'].'/id/'.$cr['cr_id'].'#fragment-3">'.$this->translate->_('edit').'</a>]'
							//.'&nbsp;&nbsp;[<a href="/portlet/management/delcontroller/prid/'.$i['pr_id'].'/id/'.$cr['cr_id'].'#fragment-3">'.$this->translate->_('delete').'</a>]'
							.'&nbsp;&nbsp;[<a href="#dlg_alert2" pr="'.$i['pr_id'].'" cr="'.$cr['cr_id'].'" rel="facebox" onclick="delEntry(this,\'cr\')">'.$this->translate->_('delete').'</a>]'
							.'</td></tr>';
							$crr++;
						}
						echo '</table>';
					}
						echo '<a href="/portlet/management/frmcontroller/prid/'.$i['pr_id'].'#fragment-3">Add a controller</a>';
				?>
				</td>
				<td class="d5" ><?php echo $i['pr_comment'];	?></td>
				<td class="d6" >
				<?php if($i['wbs_id']!=0){	?>
					<a href="/portlet/management/frmportlet/id/<?php echo $i['pr_id'];?>#fragment-3"><?php echo $this->translate->_('edit');?></a>&nbsp;|&nbsp;
					<a href="#dlg_alert" val="<?php echo $i['pr_id'];?>" rel="facebox" onclick="delEntry(this,'pr')"><?php echo $this->translate->_('delete');?></a>
				<?php }else echo 'NOT ALLOWED';	?>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,'/portlet/management/frmlist', $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('i');
	}
?>
<br />
<br />

						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<div id="dlg_alert" style="display:none;">
<?php echo $this->translate->_('l');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' onclick="delEntry('confirm', 'pr');return false;" ><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$.facebox.close();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
</div>

<div id="dlg_alert2" style="display:none;">
<?php echo $this->translate->_('ab');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' onclick="delEntry('confirm','cr');return false;" ><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$.facebox.close();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
</div>
<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$back ."' class='btn ui-state-default ui-corner-all'><font  size='2'>" 
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$this1."' class='btn'><font  size='2'>"										
								.  $translate->_('next page')."</font></a>"; 

					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
?>