<script type="text/javascript">
$(document).ready(function() {
		$("li").removeClass("ui-state-active");
		$("#tb_edit").addClass("ui-state-active");
})
</script>
<style>
.td_title
{
	width:100px;
}
.td_box
{
	width:420px;
}
#div_tbl
{
margin:0 auto;
padding:10px;
margin-top:5px;
width:650px;
border:1px solid;
height:auto;

}
</style>
	<div id="div_tbl" class="ui-corner-all ui-widget-header"><center><h1><?php echo $this->escape($this->title);?></h1></center></div>
	<form method="post" autocomplete="off" action="<?php echo $this->escape($this->action)?>" name="usereditform">
	<div id="div_tbl" class="ui-corner-all ui-widget-content" >
		<table style="width:540px; margin:0 auto;text-align:right;">
			<tr title="نام کاربر">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_fname)?> </label></td>
				<td class="td_box">	<input type="text" name="first_name" maxlength="100" size="35" class="inputBox" value="<?php echo $this->data['first_name']?>">
			</td>
		  <td></td>

			</tr>
			<tr title="نام خانوادگی کاربر">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_lname)?></label></td>
				<td class="td_box"><input type="text" name="last_name" size="35"  class="inputBox" value="<?php echo $this->data['last_name']?>"></td> 
			</tr>
			<tr title="نام کاربری یک ایمیل معتبر می باشد">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_uname)?></label></td>
				<td class="td_box"><input type="text" name="username" size="35"  class="inputBox" value="<?php echo $this->data['username']?>"></td>
			</tr>
			<tr title="کلمه عبور باید بیش از 5 کاراکتر باشد">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_pass_1)?></label></td>
				<td class="td_box"><input type="password" maxlength="100" size="35" class="inputBox" name="password_1"></td>
			</tr>
			<tr title="کلمه عبور را دوباره ">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_pass_2)?></label></td>
				<td class="td_box"><input type="password" maxlength="100" size="35" class="inputBox" name="password_2"></td> 
			</tr>
		</table>
	</div>
	<div id="div_tbl" class="ui-corner-all ui-state-highlight">
	<center>
		<span class="art-button-wrapper">
			<span class="l"> </span>
			<span class="r"> </span>
			<a  class='art-button' onclick="document.forms.usereditform.submit();"  href="#" style="width:70px;text-align:center;"><?php echo $this->label_submit;?></a>
		</span>
		<span class="art-button-wrapper ">
			<span class="l"> </span>
			<span class="r"> </span>
			<a  class='art-button' href="/rcpanel/panel/index" style="width:70px;text-align:center;">انصراف</a>
		</span>
	</center>
	</div>
	</form>