<div id="page_loginform" class="page" style="width:500px;margin:0 auto;float:none;">
<div class="art-post">
	<div class="art-post-tl"></div>
	<div class="art-post-tr"></div>
	<div class="art-post-bl"></div>
	<div class="art-post-br"></div>
	<div class="art-post-tc"></div>
	<div class="art-post-bc"></div>
	<div class="art-post-cl"></div>
	<div class="art-post-cr"></div>
	<div class="art-post-cc"></div>
	<div class="art-post-body">
<div class="art-post-inner">
				<h2 class="art-postheader">
					<span class="art-postheader"></span>
				</h2>
				<div class="art-postcontent">
					<!-- article-content -->
		<form name="loginform" action="/rcpanel/user/login" method="post">
				<table cellpadding="5" width="75%">
					<thead>
					<tr><th colspan="2" style="font-family:arial;font-size:18px;text-align:right;"><?php echo $this->title_site;?>
						<!--فرم ورود-->
					</th></tr>
					</thead>
					<tbody><tr>
					  <td class="tdtitle"><?php echo $this->translate->_('b');?>:</td>
					  <td><input type="text" name="login_username" class="frminputtxt" value="<?php echo $this->data['login_username'];?>"></td>
					</tr>
					<tr>
						<td colspan="2"><?php echo $this->translate->_('ad');?></td>
					<tr>
					  <td class="tdtitle"><?php echo $this->translate->_('c');?>:</td>
					  <td><input type="password" name="login_password" class="frminputtxt" value="<?php echo $this->data['login_password'];?>"></td>
					</tr>	
					<tr>
						<td colspan="2"><?php echo $this->translate->_('ae');?></td>
					<tr>
					<tr>
						<td colspan="2">
						</td>
					<tr>
					<tr>
						<td class="tdtitle"><?php echo $this->translate->_('z');?>:</td>
						<td><input type="text" name="captcha" class="frminputtxt" autocomplete="off"></td>
					</tr>	
					<tr>
					  <td colspan="2">
				</td>
					  <td>
					  </td>
					</tr>	
			  </tbody></table>
		</form>
	
	<center>
		<img src="/admin/public/generatecaptcha/t/<?php echo rand(0,900); ?>" style="padding: 0px; border: 0pt none;" id="siimagelogin" title="<?php echo $this->translate->_('z');?>">
		<a onclick="document.getElementById('siimagelogin').src = '/admin/public/generatecaptcha/t/'+ Math.random();return false;" title="<?php echo $this->translate->_('af');?>" href="#" tabindex="-1">
		<img border="0" onclick="this.blur()" alt="Reload Image" src="/img/refresh.png"></a> 
	</center>       					
	
	<center>
	<span class="art-button-wrapper ">
		<span class="l"> </span>
		<span class="r"> </span>
		<a  class='art-button' onclick="document.forms.loginform.submit();"  href="#" style="width:100px;text-align:center;"><?php echo $this->translate->_('a');?></a>
	</span>
	</center>

					<!-- /article-content -->
				</div>
				<div class="cleared"></div>
</div>

		<div class="cleared"></div>
	</div>
</div>

<style type="text/css">
#page_loginform .art-logo td{font-family:tahoma;font-size:12px;color:#FFFFFF;}


#page_loginform .art-post
{
  position: relative;
  z-index: 0;
  margin: 0 auto;
  min-width: 49px;
  min-height: 49px;
}

#page_loginform .art-post-body
{
  position: relative;
  z-index: 1;
  padding: 21px;
}

#page_loginform .art-post-tr, #page_loginform .art-post-tl, #page_loginform .art-post-br, #page_loginform .art-post-bl, #page_loginform .art-post-tc, #page_loginform .art-post-bc,#page_loginform .art-post-cr, #page_loginform .art-post-cl
{
  position: absolute;
  z-index: -1;
}

#page_loginform .art-post-tr, #page_loginform .art-post-tl, #page_loginform .art-post-br, #page_loginform .art-post-bl
{
  width: 88px;
  height: 88px;
  background-image: url('/modules/rcpanel/images/post_s.png');
}

#page_loginform .art-post-tl
{
  top: 0;
  left: 0;
  clip: rect(auto, 44px, 44px, auto);
}

#page_loginform .art-post-tr
{
  top: 0;
  right: 0;
  clip: rect(auto, auto, 44px, 44px);
}

#page_loginform .art-post-bl
{
  bottom: 0;
  left: 0;
  clip: rect(44px, 44px, auto, auto);
}

#page_loginform .art-post-br
{
  bottom: 0;
  right: 0;
  clip: rect(44px, auto, auto, 44px);
}

#page_loginform .art-post-tc, #page_loginform .art-post-bc
{
  left: 44px;
  right: 44px;
  height: 88px;
  background-image: url('/modules/rcpanel/images/post_h.png');
}

#page_loginform .art-post-tc
{
  top: 0;
  clip: rect(auto, auto, 44px, auto);
}

#page_loginform .art-post-bc
{
  bottom: 0;
  clip: rect(44px, auto, auto, auto);
}

#page_loginform .art-post-cr, #page_loginform .art-post-cl
{
  top: 44px;
  bottom: 44px;
  width: 88px;
  background-image: url('/modules/rcpanel/images/post_v.png');
}

#page_loginform .art-post-cr
{
  right: 0;
  clip: rect(auto, auto, auto, 44px);
}

#page_loginform .art-post-cl
{
  left: 0;
  clip: rect(auto, 44px, auto, auto);
}

#page_loginform .art-post-cc
{
  position: absolute;
  z-index: -1;
  top: 44px;
  left: 44px;
  right: 44px;
  bottom: 44px;
  background-color: #FFFFFF;
}

#page_loginform .art-post
{
  margin: 7px;
}
#page_loginform table{ float:none;margin:0 auto; direction:<?php echo $this->translate->_('dir'); ?>;}
</style>

</div>
