<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<div class="art-article" > 
	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
			<div class="art-post-inner">
				<div class="art-postmetadataheader">
					<h2 class="art-postheader">
						<span class="art-postheader"><?php echo $this->title_site; ?></span>
					</h2>
				</div>
				<div class="art-postcontent">
					<!-- article-content -->

<div class="cnt_del">
	<br />
	<center>
		<?php echo $this->translate->_('f'); ?>
	</center>
	<span class="art-button-wrapper ">
		<span class="l"> </span>
		<span class="r"> </span>
		<a  class='btn art-button' href="<?php echo $this->confirmAct; ?>" >تائید</a>
	</span>
	<span class="art-button-wrapper ">
		<span class="l"> </span>
		<span class="r"> </span>
		<a  class='btn art-button' href="/usermanager/frmlist/index<?php echo $this->env; ?>" >انصراف</a>
	</span>
	<br />
	<br />
</div>
					<!-- article-content -->
				</div>
			</div>
		</div>
	</div>
</div>
