<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  .click(function(){ $('#facebox #confirm').attr('href', '/skiner/skin/del/id/'+$(this).attr('val')); })
    })
function openPreview(sid){var pwindo = window.open('/page/11?sid='+sid, 'preview', 'location=0,scrollbars=1'); pwindo.focus();return false;}
</script>
<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;/*width:650px;border:1px solid;*/height:auto;}
.d1{width:5%;} td.d2{width:30%; text-align:center;}.d3{width:30%;}.d4{width:35%;}

</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder ui-widget" style="table-layout:fixed;width:100%;">
			<tr  class="ui-widget-header" >
			  <th class="d1" ><?php echo $this->translate->_('c');?></th>  
			  <th class="d2" ><?php echo $this->translate->_('d');?></th>
			  <th class="d3" ><?php echo $this->translate->_('title');?></th>	  
			  <th class="d4" ><?php echo $this->translate->_('e');?></th>	  
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr>
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" >
					<?php 
					$basepath	= ($i['wbs_id']!=0)?$this->docroot.'/'.WBSiD.'/files'. $i['skin_path']:$i['skin_path'];
					$scrsrc		= $basepath.'/screenshot.gif'; 
					//$fileheader	= get_headers('http://'.$_SERVER['HTTP_HOST'].$scrsrc, 1);
					//if($fileheader['Content-Type']!='image/gif')	$scrsrc	= '/flsimgs/public/images/Rimgs/screenshot.gif';
					$fileheader	= file_exists($scrsrc);
					if(!$fileheader)	$scrsrc	= '/flsimgs/public/images/Rimgs/screenshot.gif';
					
					echo '<img src="'.$scrsrc.'" width="120px" />';
					?>
				</td>
				<td class="d3" ><?php echo $i['title'];?></td>
				<td class="d4" >
					<a href="/admin/template/select/sid/<?php echo $i['skin_id']; ?>"><?php echo $this->translate->_('select');?></a>&nbsp;|&nbsp;
					<a href="#" onclick="return openPreview(<?php echo $i['skin_id'];?>);">
						<?php echo $this->translate->_('preview');?>
					</a>&nbsp;|&nbsp;
					<a href="/skiner/skin/frmregister/id/<?php echo $i['skin_id'];?>#fragment-4"><?php echo $this->translate->_('edit');?></a>&nbsp;|&nbsp;
					<a href="#dlg_link" class="sel_link" val="<?php echo $i['skin_id'];?>" name="<?php echo $i['title'];?>" rel="facebox"><?php echo $this->translate->_('delete');?></a>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,'/skiner/skin/frmlist', $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('i');
	}
?>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/skiner/template/frmlist" ><?php echo $this->translate->_('f');?></a>
</span>
<br />
<br />

						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<div id="dlg_link" style="display:none;">
<?php echo $this->translate->_('l');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" ><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$('#facebox a.close').click();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
</div>
<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$back ."' class='btn ui-state-default ui-corner-all'><font  size='2'>" 
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$this1."' class='btn ui-state-default ui-corner-all'><font  size='2'>"										
								.  $translate->_('next page')."</font></a>"; 

					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}
?>