<link rel="stylesheet" href="/css/rasta/dashboardii.css" />

<link href="/lib/facebox/v2/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/lib/facebox/v2/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox()
	  .click(function(){ $('#facebox #confirm').attr('href', '/dandelion/management/del/id/'+$(this).attr('val')); })
    })
</script>
<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;/*width:650px;border:1px solid;*/height:auto;}
.d1{width:5%;}.d2{width:22%;}.d31{width:11%;}.d32{width:11%;}.d4{width:30%;}.d5{width:20%;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg){echo  "<h4>".$msg."</h4>";}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="1" cellspacing="0"  class="showborder" style="table-layout:fixed;width:100%;">
			<tr  class="ui-widget-header" >
			  <th class="d1"><?php echo $this->translate->_('c');?></th>  
			  <th class="d2"><?php echo $this->translate->_('title');?></th>
			  <th class="d3"><?php echo $this->translate->_('status');?></th>	  
			  <th class="d3"><?php echo $this->translate->_('owner');?></th>	  
			  <th class="d4"><?php echo $this->translate->_('e');?></th>	  
			  <th class="d5"><?php echo $this->translate->_('g');?></th>	    
			</tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
			<tr>
				<td class="d1" ><?php echo $j+$this->start;?></td>		
				<td class="d2" ><?php echo $i['dn_title'];?></td>
				<td class="d31" ><?php echo ( ($i['dn_status']==1)?$this->translate->_('active'):$this->translate->_('inactive') ); ?></td>
				<td class="d32" ><?php echo ( ($i['wbs_id']==0)?$this->translate->_('public'):$this->translate->_('dedicated') ); ?></td>
				<td class="d4" ><?php echo $i['dn_md_id']; ?></td>
				
				<td class="d5" >
				<?php if($i['wbs_id']!=0 or WBSiD==='1'){ ?>
					<a href="/dandelion/management/frmregister/id/<?php echo $i['dn_id'];?>#fragment-3"><?php echo $this->translate->_('edit');?></a>&nbsp;|&nbsp;
					<a href="#dlg_scenario" class="sel_link" val="<?php echo $i['dn_id'];?>" name="<?php echo $i['dn_title'];?>" rel="facebox"><?php echo $this->translate->_('delete');?></a>
				<?php } ?>
				</td>	  
			</tr>
		<?php 
				$j++;
			}  
		?>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,$this->BaseUrl(), $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('k');
	}
?>

<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<div id="dlg_scenario" style="display:none;">
<?php echo $this->translate->_('t');?>
<br />
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a id="confirm"  class='btn art-button' href="" ><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a class='btn art-button' onclick="$('#facebox a.close').click();" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
</div>
<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/dandelion/management/frmlist/st/".$back ."' class='btn ui-state-default ui-corner-all'><font  size='2'>"
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/dandelion/management/frmlist/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/dandelion/management/frmlist/st/".$this1."' class='btn'><font  size='2'>"
								.  $translate->_('next page')."</font></a>";
					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}

?>