<script type="text/javascript">
$(document).ready(function(){
	$("#submit").click(function submitForm()
	{
		document.forms[0].submit();
		return false;
	})
})
</script>
<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
.inputBox{text-align:left;direction:ltr;}

.td_title{width:100px;text-transform:uppercase;}
.td_box{width:420px;}
.btn{margin:3px;background:#F4F4F4}
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
select.lay_select{width:200px;}
</style>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader" style="text-transform:capitalize;"><?php echo $this->title_site; ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->

	<form action="<?php echo $this->form_action;?>" method="post">
	<table style="width: 820px; margin: 0pt auto; text-align: right; direction:ltr;">
		<tbody>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('Name');?>&nbsp;<font color="#FF0000">*</font></label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="35" maxlength="100" name="name" value="<?php echo $this->data['name']; ?>">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ai');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('layout');?></label></td>
				<td class="td_box" dir="ltr">
<?php
 if(is_array($this->wbs_layouts))
{
	echo '<select name="layout" class="lay_select">';
		echo '<option value="0">&nbsp;&nbsp;&nbsp;&nbsp;</option>';
	foreach($this->wbs_layouts as $ly) 
		echo '<option value="'.$ly['ly_id'].'" '.(($ly['ly_id']==$this->data['layout'])?'selected="selected"':'').'>'.
			(($ly['wbs_id']==0)?'Public:':'Dedicated:').'&nbsp;&nbsp;'.$ly['ly_title'].'&nbsp;&nbsp;</option>';
	echo '</select>';
}
 ?>
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('comment');?> </label></td>
				<td class="td_box">
					<input type="text" class="inputBox" size="100" maxlength="300" name="comment" value="<?php echo $this->data['comment']; ?>">
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ah');?></span><br /><br />
				</td>
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('configs');?> </label></td>
				<td class="td_box"><br />
					<textarea cols="75" rows="10" dir="ltr" name="config"><?php echo htmlspecialchars($this->data['config']); ?></textarea>
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;"><?php echo $this->translate->_('af');?></span><br /><br />
				</td> 
			</tr>
			<tr>
				<td class="td_title"><label class="label"><?php echo $this->translate->_('bootstrap');?> </label></td>
				<td class="td_box"><br />
					<textarea cols="75" rows="10" dir="ltr" name="bootstrap"><?php echo htmlspecialchars($this->data['bootstrap']); ?></textarea>
					<br /><br />
					<span dir="ltr" style="font-size:90%;color:#0000CC;text-transform:capitalize;"><?php echo $this->translate->_('ag');?></span><br /><br />
				</td> 
			</tr>
		</tbody>
	</table>
	<input type="hidden" value="<?php echo $this->data['pid']; ?>" name="pid" />
	</form>
			

<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' id="submit" href="#"><?php echo $this->translate->_('ok');?></a>
</span>
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/portlet/management/frmlist#fragment-4" ><?php echo $this->translate->_('cancel');?></a>
</span>
<br />
<br />
						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>
