<link rel="stylesheet" href="/css/rasta/dashboardii.css" />
<style>
#div_tbl{margin:0 auto;padding:10px;margin-top:2px;height:auto;}
td.hideborder{ border:none 0px;}
</style>
<script>
function openPreview(sid){var pwindo = window.open('/page/11?sid='+sid, 'preview', 'location=0,scrollbars=1'); pwindo.focus();return false;}
</script>
<div class="err">
  	<?php 
		if ( !empty($this->msg))
		{
			echo '<blockquote style="color:#CC3300;line-height:1.5;">';
			foreach ($this->msg as $msg)
  			{
				   echo  "<h4>".$msg."</h4>";
			}
			echo'</blockquote>';
		}
	?>
</div>
<div id="div_tbl" class="art-article" > 

	<div class="art-post">
		<div class="art-post-tl"></div>
		<div class="art-post-tr"></div>
		<div class="art-post-bl"></div>
		<div class="art-post-br"></div>
		<div class="art-post-tc"></div>
		<div class="art-post-bc"></div>
		<div class="art-post-cl"></div>
		<div class="art-post-cr"></div>
		<div class="art-post-cc"></div>
		<div class="art-post-body">
	<div class="art-post-inner">
					<div class="art-postmetadataheader">
						<h2 class="art-postheader">
							<span class="art-postheader"><?php echo $this->escape($this->title_site); ?></span>
						</h2>
					</div>
					<div class="art-postcontent">
						<!-- article-content -->
<?php 
$data = $this->data;
	if (count($data)>0)
	{
?>
		  <table border="0" cellspacing="0"  style="table-layout:fixed;width:100%;border:none 0px;">
			<tr>
		<?php 		
			
			$j=1;
			foreach( $data as $i)
			{		
		?>
				<td class="hideborder"><table style="width:100%;">
					<tr><td><?php echo ( (strlen(trim($i['title']))>3 )?$i['title']:$this->start+$j );?></td></tr>
					<tr><td align="center">
						<?php 
						$basepath	= $i['skin_path'];
						if(!preg_match('/\/$/', $basepath))	$basepath	= $basepath.'/';
						$scrsrc		= $basepath.'screenshot.gif'; 
						echo '<img src="'.$scrsrc.'" width="170px" />';
						?>
					</td></tr>
					<tr><td>
						<a href="/admin/template/select/sid/<?php echo $i['skin_id']; ?>"><?php echo $this->translate->_('select');?></a>&nbsp;|&nbsp;
					<a href="#" onclick="return openPreview(<?php echo $i['skin_id'];?>);">
						<?php echo $this->translate->_('preview');?>
					</a>
					</td></tr>
				</table></td>
				
				<?php if(is_int($j/5) && $j!=$this->limit) echo '</tr><tr>'; ?>

		<?php 
				$j++;
			}  
			$j--;
			if(!is_int($j/5)) for($k = 1; $k <= (5 - $j + (5 * floor($j/5))); $k++) echo '<td></td>';
		?>
			</tr>
		  </table>

		<div id="pagingcontainer">
					<?php paging($this->count,$this->start,$this->limit,'/skiner/template/frmlist', $this->translate);?>
		</div>
<?php
	}
	else
	{
		echo $this->translate->_('i');
	}
?>
<br />
<span class="art-button-wrapper ">
	<span class="l"> </span>
	<span class="r"> </span>
	<a  class='btn art-button' href="/skiner/skin/frmlist#fragment-4" ><?php echo $this->translate->_('b');?></a>
</span>
<br />
<br />

						<!-- /article-content -->
					</div>
					<div class="cleared"></div>
	</div>
	
			<div class="cleared"></div>
		</div>
	</div>

</div>

<?php 
function paging	($count,$start,$limit,$BaseUrl, $translate)
{
	$paging	="";
	$this1 			= $start + $limit; 
	$back 			= $start - $limit; 
	$next 			= $start + $limit;
	if		($count > $limit )
			{
				$paging		.= ' <table align = "center"><tr><td  align="center" width="25%">';
				if	($back >= 0) 
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$back ."' class='btn ui-state-default ui-corner-all'><font  size='2'>" 
								.  $translate->_('previous page')."</font></a>"; 
					} 
				$paging	.= "</td><td align=center width='50%'>";
				$i			= 0;
				$j			= 1;
				for		($i	= 0; $i < $count; $i	= $i + $limit)
					{
						if	($i <> $start)
							{
								$paging	.= " <a href='".$BaseUrl."/st/".$i."'><font  size='2'>".$j."</font></a> ";
							}
						else 
							{ 
								$paging	.= "<font  size='4' color=red>".$j."</font>";
							}        
						$j	= $j+1;
					}
				$paging	.= "</td><td  align='center' width='25%'>";
				if	($this1 < $count)
					{ 
						$paging	.= "<a href='".$BaseUrl."/st/".$this1."' class='btn ui-state-default ui-corner-all'><font  size='2'>"										
								.  $translate->_('next page')."</font></a>"; 

					} 
				$paging	.= "</td></tr></table>";
			}
	echo $paging;
}

?>