<?php
foreach($this->result as $value)
	{
		echo '<div class="rasta-buttonset">'
			.	'<a>ویرایش</a>'
			.	'<a>مشاهده در پنجره جدید</a>'
			.	'<a class="menutitle"            menuid="'.$value['id'].'" title="'.$value['menu_title'].'">'.$value['menu_title'].'</a>'
			//.	'<a class="menutitle" type="vsm" menuid="'.$value['id'].'" title="'.$value['menu_title'].'">'.$value['menu_title'].'</a>'
			.'</div>';
	}
echo "<div><input type='hidden' id='count' value='".$this->count."' /></div>";
?>