<script type="text/javascript">
$(document).ready(function() {
		$("li").removeClass("ui-state-active");
		$("#tb_edit").addClass("ui-state-active");
})
</script>

<?php /*?><div class="ui-state-highlight ui-corner-all">
	<h1><?php echo $this->escape($this->title);?></h1>
</div>	
<?php */?>
<div class="ui-state-error ui-corner-all"><h2><?php echo $this->description; ?></h2></div>
	

<style>
.td_title
{
	width:100px;
}
.td_box
{
	width:420px;
}
#div_tbl
{
margin:0 auto;
padding:10px;
margin-top:5px;
width:650px;
border:1px solid;
height:auto;

}
</style>
	<div id="div_tbl" class="ui-corner-all ui-widget-header"><center><h1><?php echo $this->escape($this->title);?></h1></center></div>
	<form method="post" autocomplete="off" action="<?php echo $this->baseUrl().$this->escape($this->action)?>">
	<div id="div_tbl" class="ui-corner-all ui-widget-content" >
		<table style="width:540px; margin:0 auto;text-align:right;">
			<tr title="نام کاربر">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_fname)?> </label></td>
				<td class="td_box">	<input type="text" name="first_name" maxlength="100" size="35" class="inputBox" value="<?php echo $this->data['first_name']?>">
			</td>
		  <td></td>

			</tr>
			<tr title="نام خانوادگی کاربر">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_lname)?></label></td>
				<td class="td_box"><input type="text" name="last_name" size="35"  class="inputBox" value="<?php echo $this->data['last_name']?>"></td> 
			</tr>
			<tr title="نام کاربری یک ایمیل معتبر می باشد">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_uname)?></label></td>
				<td class="td_box"><input type="text" name="username" size="35"  class="inputBox" value="<?php echo $this->data['username']?>"></td>
			</tr>
			<tr title="کلمه عبور باید بیش از 5 کاراکتر باشد">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_pass_1)?></label></td>
				<td class="td_box"><input type="password" maxlength="100" size="35" class="inputBox" name="password_1"></td>
			</tr>
			<tr title="کلمه عبور را دوباره ">
				<td class="td_title"><label class="label"><?php echo $this->escape($this->label_pass_2)?></label></td>
				<td class="td_box"><input type="password" maxlength="100" size="35" class="inputBox" name="password_2"></td> 
			</tr>
		</table>
	</div>
	<div id="div_tbl" class="ui-corner-all ui-state-highlight">
	<center>
					<input type="submit" class='btn ui-state-default ui-corner-all' value="<?php echo $this->escape($this->label_submit);?>" title="تائید و ارسال فرم"/> 
					<a title="انصراف و بازگشت به صفحه اصلی" class='btn ui-state-default ui-corner-all' href="<?php echo $this->baseUrl(); ?>/godpanel/panel/index">انصراف</a>
	</center>
	</div>
	</form>